### ISSUE TITLE
widget.html is not included in the CocoaPod source files

### ISSUE THREAD

**Issue by jrendel-dil** [announcekitapp/announcekit-ios-sdk#2]
The example project works, but when I import AnnouceKit via CocoaPods, I do not get the widget.html file. 

I can see the podspec is including all source files in 'Sources/AnnounceKit/Classes/**/*' but the widget.html file is at the root of the repo.

I tried just adding the file manually to my project, but due to the way its loaded in AnnounceKitClient, it has to exist in the same bundle as AnnounceKitClient.

**Comment by seyfeddin** [comment]
Looking into it…

**Comment by namirali** [comment]
@jrendel-dil thanks for reporting the issue, it should be solved in `0.10.1`
